global:
  chartName: orders
orders:
  # Deployment object
  newDeployment:
    enabled: false
  # Updated (New) Deployment resource
  deployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: franchialan/ecommerce-orders
    imageTag: sha256:2f583bcbe27c7fd172d102ecd989e6e4c6286be6819fdad4bc89e779de3acaa8
    port: 3003
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Stable Service object
  service:
    enabled: true
    name: orders-service
    namespace: ecommerce
    appName: orders
    type: ClusterIP
    servicePort: 3003
    targetPort: 3003
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace: ecommerce
    enabled: false
  # Ingress 
  ingress:
    enabled: false
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
