global:
  chartName: orders
orders:
  # Deployment object
  newDeployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: franchialan/ecommerce-orders
    imageTag: sha256:2f26d4a24cd7e87becd4fe933b2144b7972bc82203fced5fa56a2a0bb2970d9b
    port: 3003
  # Stable Service object
  service:
    enabled: true
    name: orders-service
    namespace: ecommerce
    appName: orders
    type: ClusterIP
    servicePort: 3003
    targetPort: 3003
  # Canary Service object
  canaryService:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: true
    name: orders
    namespace: ecommerce
    host: nip.io
    path: "/"
    serviceName: orders-service
    servicePort: 3003
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Canary Rollout
  canaryRollout:
    enabled: false
